name: Approval

permissions:
  pull-requests: write

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - ready_for_review

jobs:
  approval:
    runs-on: ubuntu-latest
    needs: [linting, build]
    if: needs.linting.result == 'success' && needs.build.result == 'success'
    steps:
      - uses: hmarr/auto-approve-action@v3
        with:
          review-message: "Auto-approved by ${{ github.actor }}"