name: Build

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - '*'     # Listen to all branches

env:
  NODE_VERSION: 16

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Code Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn run build